AboudyKreidieh/h-baselines

- hbaselines/goal_conditioned/base.py
Last we spoke, the dynamics training was diverging. I corrected a few implementation mistakes, and also changed the model training to adhere more strictly to what PETS does.
> fixed instability bug in dynamics model

- README.md
- README.tex.md
- hbaselines/algorithms/off_policy.py
- hbaselines/goal_conditioned/base.py
- hbaselines/goal_conditioned/replay_buffer.py
- hbaselines/goal_conditioned/sac.py
- hbaselines/goal_conditioned/td3.py
- tests/fast_tests/test_policy.py
> Hierarchical replay buffer

- hbaselines/fcnet/replay_buffer.py
- hbaselines/goal_conditioned/base.py
- hbaselines/goal_conditioned/replay_buffer.py
- hbaselines/goal_conditioned/sac.py
- hbaselines/goal_conditioned/td3.py
- tests/fast_tests/test_algorithm.py
- tests/fast_tests/test_policy.py
- tests/fast_tests/test_replay_buffer.py
> Hierarchical replay buffer 2

- hbaselines/utils/env_util.py
> bug fix when not using str

- .travis.yml
- hbaselines/envs/mixed_autonomy/core.py
- hbaselines/envs/mixed_autonomy/envs/av.py
- hbaselines/envs/mixed_autonomy/envs/av_multi.py
- hbaselines/envs/mixed_autonomy/params/highway_single.py
- hbaselines/envs/mixed_autonomy/params/ring.py
- hbaselines/goal_conditioned/base.py
- hbaselines/utils/env_util.py
- tests/fast_tests/test_envs.py
- tests/fast_tests/test_utils.py
> Highway single

- hbaselines/algorithms/off_policy.py
- hbaselines/envs/mixed_autonomy/envs/av.py
- hbaselines/envs/mixed_autonomy/params/highway_single.py
- hbaselines/fcnet/td3.py
- hbaselines/multi_fcnet/td3.py
- tests/fast_tests/test_utils.py
> some cleanup from the imitation branch

- hbaselines/base_policies/__init__.py
- hbaselines/base_policies/imitation.py
- tests/fast_tests/test_base_policy.py
> added base imitation learning policy

- hbaselines/algorithms/dagger.py
- hbaselines/fcnet/imitation.py
- tests/fast_tests/test_fcnet.py
> Imitation fcnet

- hbaselines/algorithms/off_policy.py
- hbaselines/algorithms/utils.py
- tests/fast_tests/test_goal_conditioned.py
> moved some alg static methods to utils

- README.md
- README.tex.md
> Readme update

- README.md
- README.tex.md
> Antgather update

- hbaselines/envs/efficient_hrl/ant.py
- hbaselines/envs/efficient_hrl/ant_maze_env.py
- hbaselines/envs/efficient_hrl/envs.py
> AntFall fix

- hbaselines/envs/mixed_autonomy/envs/av.py
- hbaselines/envs/mixed_autonomy/envs/av_multi.py
- tests/fast_tests/test_envs.py
> Updated Flow actions to never request negative speeds

- .coveragerc
- hbaselines/envs/efficient_hrl/envs.py
- hbaselines/envs/hac/envs.py
- hbaselines/envs/mixed_autonomy/envs/av_multi.py
- hbaselines/envs/mixed_autonomy/params/highway.py
- hbaselines/envs/mixed_autonomy/params/i210.py
- hbaselines/envs/mixed_autonomy/params/merge.py
- hbaselines/envs/mixed_autonomy/params/ring.py
- hbaselines/envs/point2d.py
- hbaselines/fcnet/sac.py
- hbaselines/goal_conditioned/base.py
- hbaselines/goal_conditioned/replay_buffer.py
- hbaselines/goal_conditioned/sac.py
- hbaselines/goal_conditioned/td3.py
- hbaselines/multi_fcnet/sac.py
- hbaselines/multi_fcnet/td3.py
- hbaselines/utils/env_util.py
- hbaselines/utils/tf_util.py
- requirements.txt
- tests/fast_tests/test_envs.py
- tests/fast_tests/test_fcnet.py
- tests/fast_tests/test_utils.py
- tests/slow_tests/test_experiments.py
> resolved some TODOs and FIXMEs

- hbaselines/multi_fcnet/sac.py
- hbaselines/multi_fcnet/td3.py
- tests/fast_tests/test_multi_fcnet.py
- **Kind of changes**: Incorporates base multiagent tests.
- **Related PR or issue**: None
- **Prerequisite PRs**: None
- **Related Files**:
- tests/fast_tests/test_multi_fcnet.py
> Multiagent tests

- hbaselines/envs/mixed_autonomy/envs/av.py
- hbaselines/envs/mixed_autonomy/envs/av_multi.py
- hbaselines/envs/mixed_autonomy/params/highway.py
- hbaselines/envs/mixed_autonomy/params/i210.py
- hbaselines/envs/mixed_autonomy/params/ring.py
- tests/fast_tests/test_envs.py
- **Kind of changes**: Adds support for variable inflows update reset in open Flow environments.
- **Related PR or issue**: None
- **Prerequisite PRs**: None
- **Related Files**:
- hbaselines/envs/mixed_autonomy/envs/av.py
- hbaselines/envs/mixed_autonomy/envs/av_multi.py
- hbaselines/envs/mixed_autonomy/params/highway.py
- hbaselines/envs/mixed_autonomy/params/i210.py
- tests/fast_test/test_envs.py
> Variable inflows

- hbaselines/algorithms/off_policy.py
- hbaselines/utils/sampler.py
- tests/slow_tests/test_experiments.py
> Ray sampler

- experiments/README.md
- tests/fast_tests/test_envs.py
> updated README in experiments folder

- experiments/README.md
- hbaselines/algorithms/off_policy.py
- hbaselines/algorithms/utils.py
- hbaselines/base_policies/actor_critic.py
- hbaselines/envs/mixed_autonomy/envs/av_multi.py
- hbaselines/fcnet/sac.py
- hbaselines/fcnet/td3.py
- hbaselines/goal_conditioned/base.py
- hbaselines/goal_conditioned/sac.py
- hbaselines/goal_conditioned/td3.py
- hbaselines/utils/env_util.py
- hbaselines/utils/sampler.py
- hbaselines/utils/train.py
- tests/fast_tests/test_algorithm.py
- tests/fast_tests/test_base_policies.py
- tests/fast_tests/test_goal_conditioned.py
- tests/fast_tests/test_utils.py
> removed mentions of fingerprints and centralized_value_functions

- hbaselines/algorithms/off_policy.py
- hbaselines/envs/efficient_hrl/ant_maze_env.py
- hbaselines/fcnet/sac.py
- hbaselines/fcnet/td3.py
> minor cleanup

- README.md
- README.tex.md
- experiments/run_eval.py
- experiments/run_fcnet.py
- experiments/run_hrl.py
- experiments/run_multi_fcnet.py
- experiments/run_multi_hrl.py
- hbaselines/algorithms/__init__.py
- hbaselines/algorithms/off_policy.py
- hbaselines/algorithms/rl_algorithm.py
- hbaselines/multiagent/base.py
- hbaselines/utils/train.py
- tests/fast_tests/test_algorithm.py
- tests/fast_tests/test_base_policies.py
- tests/fast_tests/test_fcnet.py
- tests/fast_tests/test_goal_conditioned.py
- tests/fast_tests/test_multiagent.py
- tests/fast_tests/test_utils.py
> Renamed OffPolicyRLAlgorithm -> RLAlgorithm

- hbaselines/envs/snn4hrl/envs.py
- hbaselines/envs/snn4hrl/snake_gather.py
- hbaselines/utils/env_util.py
> added SnakeGather environment

- hbaselines/envs/mixed_autonomy/envs/av.py
- hbaselines/envs/mixed_autonomy/envs/av_multi.py
- hbaselines/envs/mixed_autonomy/envs/utils.py
> reduced code duplication in mixed autonomy envs

- experiments/run_eval.py
- hbaselines/multiagent/base.py
- hbaselines/multiagent/h_sac.py
- hbaselines/multiagent/h_td3.py
> Multiagent fixes

- hbaselines/base_policies/__init__.py
- hbaselines/base_policies/actor_critic.py
- hbaselines/base_policies/on_policy.py
- hbaselines/fcnet/ppo.py
> added Base on-policy object

- hbaselines/envs/mixed_autonomy/envs/av_multi.py
> bug fix to observation type

- hbaselines/utils/env_util.py
> minor import error

- experiments/run_fcnet.py
- experiments/run_hrl.py
- experiments/run_multi_fcnet.py
- experiments/run_multi_hrl.py
- hbaselines/algorithms/rl_algorithm.py
- hbaselines/goal_conditioned/base.py
- hbaselines/goal_conditioned/sac.py
- hbaselines/goal_conditioned/td3.py
- hbaselines/multiagent/h_sac.py
- hbaselines/multiagent/h_td3.py
- hbaselines/utils/train.py
- tests/fast_tests/test_algorithm.py
- tests/fast_tests/test_goal_conditioned.py
- tests/fast_tests/test_multiagent.py
- tests/fast_tests/test_utils.py
> Pretraining multilevel hierarchies

- hbaselines/envs/mixed_autonomy/envs/av.py
- hbaselines/envs/mixed_autonomy/envs/av_multi.py
- hbaselines/envs/mixed_autonomy/params/highway.py
- hbaselines/envs/mixed_autonomy/params/i210.py
- hbaselines/envs/mixed_autonomy/params/ring.py
- tests/fast_tests/test_envs.py
> updated av reward

- environment.yml
- requirements.txt
- tests/fast_tests/test_envs.py
- tests/fast_tests/test_fcnet.py
> removed non-deterministic tests

- .github/workflows/ci.yml
- tests/fast_tests/test_utils.py
> Updated GitHub Actions

- README.md
- README.tex.md
- hbaselines/envs/mixed_autonomy/params/highway.py
- hbaselines/envs/mixed_autonomy/params/i210.py
- hbaselines/envs/mixed_autonomy/params/ring.py
- hbaselines/utils/env_util.py
- tests/fast_tests/test_envs.py
- tests/fast_tests/test_utils.py
> Updated envs

- README.md
- README.tex.md
- experiments/README.md
- hbaselines/algorithms/rl_algorithm.py
- hbaselines/base_policies/policy.py
- hbaselines/fcnet/ppo.py
- hbaselines/fcnet/sac.py
- hbaselines/fcnet/td3.py
- hbaselines/multiagent/sac.py
- hbaselines/multiagent/td3.py
- hbaselines/utils/tf_util.py
- hbaselines/utils/train.py
- tests/fast_tests/test_utils.py
> Batchnorm dropout

- experiments/run_fcnet.py
- experiments/run_hrl.py
- experiments/run_multi_fcnet.py
- experiments/run_multi_hrl.py
- hbaselines/algorithms/rl_algorithm.py
- hbaselines/envs/mixed_autonomy/envs/ring_nonflow.py
- hbaselines/utils/train.py
- tests/fast_tests/test_envs.py
- tests/fast_tests/test_utils.py
> Change Max Accel to 1

- experiments/run_eval.py
- hbaselines/envs/deeploco/envs.py
- hbaselines/utils/env_util.py
> Biped visualization

- README.md
- README.tex.md
> updated citation
